---
title: "Filtering"
author: "Carles  i Liam"
date: "17/02/2023"
output:
  html_document:
    theme: readable
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::include_graphics
options(width = 50)
```

# Opening a new project:

## Necessary libraries:

```{r, message=FALSE, warning=FALSE}
#install.packages("plyr") 
library(plyr)
library(vegan)
# library(scales)
# library(RColorBrewer)
# library(VennDiagram)
# library(gplots)
# library(ggplot2)
# library(ggpubr)
# library(car)
# library(pairwiseAdonis)
# library(ggVennDiagram)
# library(ggplot2)
# library(eulerr)
# library(devtools)
# library(wrapr)
 library(tidyr)
 library(dplyr)
 library(reshape)
 library(reshape2)
 library(data.table)
# devtools::install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
# library(pairwiseAdonis)
# library(tibble)
 library(tidyverse)
 library(dtplyr)
# install.packages("rlang")
# library(rlang)
# sessionInfo()
if (!require("rstudioapi")){
  install.packages("rstudioapi", dependencies = TRUE)
  library(rstudioapi)}
```

### Data:

```{r}
setwd(dirname(getActiveDocumentContext()$path))
data <-read.csv("asv_taxonomy_liam.csv", sep=",", header=T, stringsAsFactors = F)
asv.ID <- data$ASV.ID
taxonomia <- data$Taxonomy......
codes<-read.delim("metadata_liam.txt", header = TRUE, sep = "\t", dec = ".")
taxo <- read.delim("taxonomia_corregida.csv", header = TRUE, sep = ",")
taxo[taxo == ''] <- "indet"
taxo[taxo == ' '] <- "indet"
# codes<-read.table("metadata_liam.txt", header=T, skipNul = T, sep = "\t")


codes <- codes[codes$TISSUE!= "DIGESTIVE",] 
codes <- codes[codes$POP!="BAR",]
codes <- codes[codes$STAGE!="JUV",]
codes <- codes[order(codes$ID),]

codes_table <- codes[,c(1:8)]
# write.table(codes_table, "metadata_table.txt", sep= "\t")

# write.table(codes, "metadata_filtered.txt", sep= "\t")

# We are left with only the numeric columns
data<-data[,-c(1,212)]


#We are left only with samples from TUNIC&GILL&WATER and BLA&VIL:
microt<- t(data)
microt <- cbind(microt, ID=rownames(microt))
microt <- merge(microt, codes, by="ID")
microt <- as.data.frame(microt)
microt <- microt[codes$TISSUE!= "DIGESTIVE",]
microt <- microt[codes$STAGE!="JUV",]
microt <- microt[codes$POP!="BAR",]# Good Matrix for my data set
microt<- na.omit(microt)

rownames(microt) <- microt[,1]
microt <- microt[,-1]
micro <- t(microt)
names(micro)<- rownames(microt)
rownames(micro) <- colnames(microt)

micro <- as.data.frame(apply(micro, 2, as.numeric)) 
micro<- na.omit(micro)
micro <- micro[1:39753,]


micro$ID <- taxo$Class
micro$Kingdom <- taxo$Kingdom
micro$ASV <- asv.ID
microASV <- micro
micro <- micro[,c(1:210)]
rownames(micro) <- asv.ID
# micro <- as.data.frame(micro)

micro <- micro[microASV$Kingdom=="Bacteria",]
micro <- micro[rowSums(micro)>1,]
ASVlist <- rownames(micro)
ASVlist <- as.vector(ASVlist)

micro <- microASV[microASV$ASV %in% ASVlist,]
rownames(micro) <- 1:nrow(micro)

taxo2 <- taxo
taxo2 <- taxo2[taxo2$Kingdom=="Bacteria",]
taxo2 <- taxo2[taxo2$ASV.ID %in% ASVlist,]

# write.table(micro, "asv_taxonomy_liam_abundance.txt", sep= "\t")
# write.csv(taxo2, "taxonomia_final.csv", sep= "\t")

# Relative Frequency
microrf<-as.data.frame(proportions(as.matrix(micro[,1:210]),2))
microrf$ID <- micro$ID
microrf$ASV <- micro$ASV
# write.table(microrf, "asv_taxonomy_liam_relativefreq.txt", sep= "\t")

#Binary Matrix:
microb <- micro[,c(1:210)]
microb <- as.data.frame(microb)
microb[microb>0] <- 1


microb <- as.data.frame(microb)

# write.table(microb, "asv_taxonomy_liam_binary.txt", sep= "\t")
```

```{r}
##### Fem Circos #####
Circos<-aggregate(micro[,1:210],list(micro$ID),sum)
names(Circos)[1]<-"ID"
write.table(Circos, file="circos_raw.csv", sep = " ")
```

